#!/usr/bin/python

# what's your name?
print "what's your name? ", # trailing comma suppresses newline
var =  raw_input() # get input
print "hello", var, "nice to meet you :)"

# what do you like to do?
print "what do you like to do? ",
var = raw_input()
print var, "? I like to do that as well!"

# what to you like to eat?
print "what do you like to eat? ",
var = raw_input()
print var, "? I like to eat that as well!"

print "what's the temperature today? ",
var = raw_input()

if var.isdigit():
    if float(var) >= 30:
        print "this is not possible!"
    else:
        print "i like that temperature :)"
else:
    print "I NEED A NUMBER!"

